#!/bin/bash
# ========================================================================
# Removes the user data directories listed in the credentials JSON file
# generated by eda_server_start.sh
#
# SPDX-FileCopyrightText: 2026 Harald Pretl
# Johannes Kepler University, Department for Integrated Circuits
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# SPDX-License-Identifier: Apache-2.0
# ========================================================================

# Variables for script control
DEBUG=0
FORCE=0
DRY_RUN=0
CREDENTIAL_FILE=""

_usage () {
    echo
    echo "Remove user data directories listed in the credentials JSON file"
    echo "generated by eda_server_start.sh (ICD@JKU)"
    echo
    echo "Usage: $0 [-h] [-d] [-y] [-n] <credentials_file.json>"
    echo
    echo "       -h shows a help screen"
    echo "       -d enables the debug mode"
    echo "       -y do not ask for confirmation (force removal)"
    echo "       -n dry-run: print the rm commands without executing them"
    echo
}

# Process input parameters
while getopts "hdyn" flag; do
    case $flag in
        d)
            echo "[INFO] DEBUG is enabled!"
            DEBUG=1
            ;;
        y)
            [ "$DEBUG" = 1 ] && echo "[INFO] Flag -y is set."
            FORCE=1
            ;;
        n)
            [ "$DEBUG" = 1 ] && echo "[INFO] Flag -n is set (dry-run)."
            DRY_RUN=1
            ;;
        h)
            _usage
            exit 0
            ;;
        *)
            echo "[ERROR] Invalid option!"
            _usage
            exit 1
            ;;
    esac
done
shift $((OPTIND-1))

# The JSON file is the positional argument
if [ "$#" -lt 1 ]; then
    echo "[ERROR] Missing credentials JSON file argument!"
    _usage
    exit 1
fi
CREDENTIAL_FILE="$1"

# Check dependencies
if ! command -v jq >/dev/null 2>&1; then
    echo "[ERROR] The program jq is not installed!"
    exit 1
fi

# Check the input file
if [ ! -f "$CREDENTIAL_FILE" ]; then
    echo "[ERROR] Credentials file <$CREDENTIAL_FILE> not found!"
    exit 1
fi
if [ ! -r "$CREDENTIAL_FILE" ]; then
    echo "[ERROR] Credentials file <$CREDENTIAL_FILE> is not readable!"
    exit 1
fi

# Validate JSON
if ! jq empty "$CREDENTIAL_FILE" >/dev/null 2>&1; then
    echo "[ERROR] File <$CREDENTIAL_FILE> is not valid JSON!"
    exit 1
fi

# Extract data directories
mapfile -t DATADIRS < <(jq -r '.[].datadir // empty' "$CREDENTIAL_FILE")

if [ "${#DATADIRS[@]}" -eq 0 ]; then
    echo "[INFO] No data directories found in <$CREDENTIAL_FILE>."
    exit 0
fi

[ "$DEBUG" = 1 ] && echo "[INFO] Found ${#DATADIRS[@]} data directory entries."

# Ask for confirmation unless forced or in dry-run mode
if [ "$DRY_RUN" = 1 ]; then
    echo "[INFO] Dry-run mode enabled, no directories will be removed."
fi
if [ "$FORCE" = 0 ] && [ "$DRY_RUN" = 0 ]; then
    echo "[WARNING] The following directories will be permanently removed:"
    for d in "${DATADIRS[@]}"; do
        echo "          $d"
    done
    echo
    read -r -p "Are you sure you want to continue? [y/N] " ANSWER
    case "$ANSWER" in
        y|Y|yes|YES)
            ;;
        *)
            echo "[INFO] Aborted by user."
            exit 0
            ;;
    esac
fi

SUCCESSFUL=0
FAILED=0
SKIPPED=0

for DATADIR in "${DATADIRS[@]}"; do
    if [ -z "$DATADIR" ]; then
        [ "$DEBUG" = 1 ] && echo "[INFO] Skipping empty data directory entry."
        ((SKIPPED++))
        continue
    fi

    # Safety checks to avoid catastrophic removals
    case "$DATADIR" in
        /|/bin|/boot|/dev|/etc|/home|/lib|/lib32|/lib64|/opt|/proc|/root|/run|/sbin|/srv|/sys|/tmp|/usr|/var)
            echo "[ERROR] Refusing to remove critical system directory <$DATADIR>!"
            ((FAILED++))
            continue
            ;;
    esac

    if [ ! -e "$DATADIR" ]; then
        echo "[INFO] Directory <$DATADIR> does not exist, skipping."
        ((SKIPPED++))
        continue
    fi

    if [ ! -d "$DATADIR" ]; then
        echo "[ERROR] <$DATADIR> is not a directory, skipping!"
        ((FAILED++))
        continue
    fi

    if [ "$DRY_RUN" = 1 ]; then
        echo "[DRY-RUN] rm -rf -- $DATADIR"
        ((SUCCESSFUL++))
        continue
    fi

    [ "$DEBUG" = 1 ] && echo "[INFO] Removing <$DATADIR>..."
    if rm -rf -- "$DATADIR"; then
        echo "[INFO] Removed <$DATADIR>."
        ((SUCCESSFUL++))
    else
        echo "[ERROR] Failed to remove <$DATADIR>!"
        ((FAILED++))
    fi
done

echo
if [ "$DRY_RUN" = 1 ]; then
    echo "[INFO] Summary (dry-run): $SUCCESSFUL would be removed, $SKIPPED skipped, $FAILED failed."
else
    echo "[INFO] Summary: $SUCCESSFUL removed, $SKIPPED skipped, $FAILED failed."
fi
if [ "$FAILED" -gt 0 ]; then
    if [ "$DRY_RUN" = 1 ]; then
        echo "[WARNING] Some directories would not be removable. Check the logs above."
    else
        echo "[WARNING] Some directories could not be removed. Check the logs above."
    fi
    exit 1
fi
echo "[DONE] Bye!"
exit 0
