#!/bin/bash
# ========================================================================
# Backs up the user data directories listed in the credentials JSON file
# generated by eda_server_start.sh into a single .tar.gz archive.
#
# SPDX-FileCopyrightText: 2023-2026 Harald Pretl
# Johannes Kepler University, Department for Integrated Circuits
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# SPDX-License-Identifier: Apache-2.0
# ========================================================================

# Variables for script control
DEBUG=0
DRY_RUN=0
SPLIT_ARCHIVES=0
OUTPUT_FILE=""
CREDENTIAL_FILE=""

_usage () {
    echo
    echo "Back up user data directories listed in the credentials JSON file"
    echo "generated by eda_server_start.sh (ICD@JKU)"
    echo
    echo "Usage: $0 [-h] [-d] [-n] [-s] [-o output.tar.gz] <credentials_file.json>"
    echo
    echo "       -h shows a help screen"
    echo "       -d enables the debug mode"
    echo "       -n dry-run: print the tar commands without executing them"
    echo "       -s split: create one .tar.gz per user/data dir instead of a combined archive"
    echo "       -o sets the output archive name (default: eda_backup_<timestamp>.tar.gz)"
    echo "          With -s, this is treated as a prefix (default: eda_backup_<timestamp>)"
    echo
}

# Process input parameters
while getopts "hdnso:" flag; do
    case $flag in
        d)
            echo "[INFO] DEBUG is enabled!"
            DEBUG=1
            ;;
        n)
            [ "$DEBUG" = 1 ] && echo "[INFO] Flag -n is set (dry-run)."
            DRY_RUN=1
            ;;
        s)
            [ "$DEBUG" = 1 ] && echo "[INFO] Flag -s is set (split archives)."
            SPLIT_ARCHIVES=1
            ;;
        o)
            [ "$DEBUG" = 1 ] && echo "[INFO] Flag -o is set to $OPTARG."
            OUTPUT_FILE=${OPTARG}
            ;;
        h)
            _usage
            exit 0
            ;;
        *)
            echo "[ERROR] Invalid option!"
            _usage
            exit 1
            ;;
    esac
done
shift $((OPTIND-1))

# The JSON file is the positional argument
if [ "$#" -lt 1 ]; then
    echo "[ERROR] Missing credentials JSON file argument!"
    _usage
    exit 1
fi
CREDENTIAL_FILE="$1"

# Check dependencies
if ! command -v jq >/dev/null 2>&1; then
    echo "[ERROR] The program jq is not installed!"
    exit 1
fi
if ! command -v tar >/dev/null 2>&1; then
    echo "[ERROR] The program tar is not installed!"
    exit 1
fi

# Check the input file
if [ ! -f "$CREDENTIAL_FILE" ]; then
    echo "[ERROR] Credentials file <$CREDENTIAL_FILE> not found!"
    exit 1
fi
if [ ! -r "$CREDENTIAL_FILE" ]; then
    echo "[ERROR] Credentials file <$CREDENTIAL_FILE> is not readable!"
    exit 1
fi

# Validate JSON
if ! jq empty "$CREDENTIAL_FILE" >/dev/null 2>&1; then
    echo "[ERROR] File <$CREDENTIAL_FILE> is not valid JSON!"
    exit 1
fi

# Build default output name if not given
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
if [ -z "$OUTPUT_FILE" ]; then
    if [ "$SPLIT_ARCHIVES" = 1 ]; then
        OUTPUT_FILE="eda_backup_${TIMESTAMP}"
    else
        OUTPUT_FILE="eda_backup_${TIMESTAMP}.tar.gz"
    fi
fi

# Extract data directories (and matching user names for split mode)
mapfile -t DATADIRS < <(jq -r '.[].datadir // empty' "$CREDENTIAL_FILE")
mapfile -t USERS    < <(jq -r '.[].user    // empty' "$CREDENTIAL_FILE")

if [ "${#DATADIRS[@]}" -eq 0 ]; then
    echo "[INFO] No data directories found in <$CREDENTIAL_FILE>."
    exit 0
fi

[ "$DEBUG" = 1 ] && echo "[INFO] Found ${#DATADIRS[@]} data directory entries."

SUCCESSFUL=0
FAILED=0
SKIPPED=0

# Collect valid existing directories
VALID_DIRS=()
VALID_USERS=()
for i in "${!DATADIRS[@]}"; do
    DATADIR="${DATADIRS[$i]}"
    USERNAME="${USERS[$i]:-user$i}"

    if [ -z "$DATADIR" ]; then
        [ "$DEBUG" = 1 ] && echo "[INFO] Skipping empty data directory entry."
        ((SKIPPED++))
        continue
    fi
    if [ ! -e "$DATADIR" ]; then
        echo "[INFO] Directory <$DATADIR> does not exist, skipping."
        ((SKIPPED++))
        continue
    fi
    if [ ! -d "$DATADIR" ]; then
        echo "[ERROR] <$DATADIR> is not a directory, skipping!"
        ((FAILED++))
        continue
    fi
    if [ ! -r "$DATADIR" ]; then
        echo "[ERROR] Directory <$DATADIR> is not readable, skipping!"
        ((FAILED++))
        continue
    fi
    VALID_DIRS+=("$DATADIR")
    VALID_USERS+=("$USERNAME")
done

if [ "${#VALID_DIRS[@]}" -eq 0 ]; then
    echo "[WARNING] No valid data directories to back up."
    echo "[INFO] Summary: $SUCCESSFUL archived, $SKIPPED skipped, $FAILED failed."
    exit 1
fi

if [ "$DRY_RUN" = 1 ]; then
    echo "[INFO] Dry-run mode enabled, no archive will be written."
fi

if [ "$SPLIT_ARCHIVES" = 1 ]; then
    # One archive per directory
    for i in "${!VALID_DIRS[@]}"; do
        DATADIR="${VALID_DIRS[$i]}"
        USERNAME="${VALID_USERS[$i]}"
        ARCHIVE="${OUTPUT_FILE}_${USERNAME}.tar.gz"

        PARENT=$(dirname -- "$DATADIR")
        BASE=$(basename -- "$DATADIR")

        if [ "$DRY_RUN" = 1 ]; then
            echo "[DRY-RUN] tar -czf $ARCHIVE -C $PARENT $BASE"
            ((SUCCESSFUL++))
            continue
        fi

        [ "$DEBUG" = 1 ] && echo "[INFO] Archiving <$DATADIR> to <$ARCHIVE>..."
        if tar -czf "$ARCHIVE" -C "$PARENT" "$BASE"; then
            echo "[INFO] Archived <$DATADIR> to <$ARCHIVE>."
            ((SUCCESSFUL++))
        else
            echo "[ERROR] Failed to archive <$DATADIR>!"
            rm -f -- "$ARCHIVE"
            ((FAILED++))
        fi
    done
else
    # Single combined archive (use absolute paths via -P to preserve full layout)
    if [ "$DRY_RUN" = 1 ]; then
        echo "[DRY-RUN] tar -czPf $OUTPUT_FILE ${VALID_DIRS[*]}"
        SUCCESSFUL=${#VALID_DIRS[@]}
    else
        [ "$DEBUG" = 1 ] && echo "[INFO] Archiving ${#VALID_DIRS[@]} directories into <$OUTPUT_FILE>..."
        if tar -czPf "$OUTPUT_FILE" "${VALID_DIRS[@]}"; then
            echo "[INFO] Archive <$OUTPUT_FILE> created successfully."
            SUCCESSFUL=${#VALID_DIRS[@]}
        else
            echo "[ERROR] Failed to create archive <$OUTPUT_FILE>!"
            rm -f -- "$OUTPUT_FILE"
            FAILED=${#VALID_DIRS[@]}
        fi
    fi
fi

echo
if [ "$DRY_RUN" = 1 ]; then
    echo "[INFO] Summary (dry-run): $SUCCESSFUL would be archived, $SKIPPED skipped, $FAILED failed."
else
    echo "[INFO] Summary: $SUCCESSFUL archived, $SKIPPED skipped, $FAILED failed."
fi
if [ "$FAILED" -gt 0 ]; then
    echo "[WARNING] Some directories could not be backed up. Check the logs above."
    exit 1
fi
echo "[DONE] Bye!"
exit 0
